// import { ClerkProvider } from "@clerk/nextjs"
import '../globals.css'
import { Inter } from "next/font/google";
import LeftSideBar from "@/components/layout/LeftSideBar";
import TopBar from "@/components/layout/TopBar";
import MainContainer from "@/components/layout/MainContainer";
import RightSideBar from "@/components/layout/RightSideBar";
import BottomBar from "@components/layout/BottomBar";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={`${inter.className} bg-purple-2 text-light-1`}>
        <main className="flex flex-row">
        <LeftSideBar/>
          <MainContainer>
           
        {children}
        
        </MainContainer>
        
        </main>
        <BottomBar/>
        </body>
        
    </html>
    
  )
}
